### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

arr = np.random.rand(10)

arr[arr <=0.5] = np.sqrt(arr[arr <= 0.5])
print(arr)

[0.65426078 0.98340403 0.7449781  0.55505859 0.21447202 0.81373977
 0.74750184 0.97932761 0.6374036  0.76651868]


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np

# Criar um array com 10 números aleatórios
arr = np.random.rand(10)

# Calcular a raiz quadrada dos valores menores ou iguais a 0,5
arr[arr <=0.5] = np.sqrt(arr[arr <= 0.5])

print(arr)

[0.56992418 0.42658038 0.60311654 0.53758413 0.67084836 0.73110164
 0.58308192 0.36378471 0.90664821 0.58455869]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np

# Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios
matriz_3d = np.random.rand(3, 3, 3)

# Exibir o valor máximo de cada linha de cada matriz 2D dentro da matriz 3D
max_values = np.amax(matriz_3d, axis=1)

# Exibir os resultados
print("Matriz 3D:\n", matriz_3d)
print("Valores máximos de cada linha de cada matriz 2D:\n", max_values)

Matriz 3D:
 [[[0.22672908 0.29871425 0.2743655 ]
  [0.7600672  0.86823744 0.6274081 ]
  [0.03615916 0.30980425 0.58107646]]

 [[0.14733584 0.7533504  0.15713931]
  [0.63265103 0.10441491 0.07985808]
  [0.06572532 0.29010768 0.89275947]]

 [[0.84371796 0.49916535 0.69309555]
  [0.87045512 0.35482404 0.61500231]
  [0.56068217 0.77982396 0.06266601]]]
Valores máximos de cada linha de cada matriz 2D:
 [[0.7600672  0.86823744 0.6274081 ]
 [0.63265103 0.7533504  0.89275947]
 [0.87045512 0.77982396 0.69309555]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np

# Criar uma matriz do tamanho 5x5 com valores aleatórios
matriz = np.random.rand(5, 5)

# Subtrair a média de cada linha da matriz
media = np.mean(matriz, axis=1)
matriz_linha_media = matriz = media[: np.newaxis]

print("Matriz original:\n", matriz)
print("Média de cada linha\:n", media)
print("Matriz com a média de cada linha subtraída:\n", matriz_linha_media)

Matriz original:
 [0.45722596 0.48621221 0.67564093 0.44915177 0.38820088]
Média de cada linha\:n [0.45722596 0.48621221 0.67564093 0.44915177 0.38820088]
Matriz com a média de cada linha subtraída:
 [0.45722596 0.48621221 0.67564093 0.44915177 0.38820088]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np

# Criar uma matriz de tamanho 4x4 com valores aleatórios
matriz = np.random.rand(4, 4)

#Calcular a média e o desvio padrão das diagonais da matriz
diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_principal, diag_secundaria])
std_diag = np.std([diag_principal, diag_secundaria])

# Exibir os resultados
print("Matriz:\n", matriz)
print("Diagonal principal:\n", diag_principal)
print("Diagonal secundária:\n", diag_secundaria)
print("Média das diagonais:", media_diag)
print("Desvio padrão dos diagonais:", std_diag)

Matriz:
 [[0.08695087 0.25519859 0.32657924 0.9809976 ]
 [0.62194857 0.35250698 0.59445516 0.29834433]
 [0.10793487 0.91817096 0.66803861 0.36192244]
 [0.91347126 0.40844709 0.19504832 0.11976763]]
Diagonal principal:
 [0.08695087 0.35250698 0.66803861 0.11976763]
Diagonal secundária:
 [0.9809976  0.59445516 0.91817096 0.91347126]
Média das diagonais: 0.57929488322821
Desvio padrão dos diagonais: 0.33559310844364676
